[versions]
jacoco = "0.8.15"
sonarqube = "7.5.0.8588"
java = "25"
pmd = "7.28.0"
errorprone-plugin = "5.1.1"
nullaway-plugin = "3.2.0"
spotless = "8.10.3"

spotbugs = "6.5.12"
spotbugs-annotations = "4.10.4"
findsecbugs = "1.14.0"

liberty-plugin = "4.0.2"
openliberty = "26.0.0.9"

jakartaee = "11.0.0"

slf4j = "2.0.20"
logback = "1.6.4"

mongodb-driver = "5.13.0"
nimbus-jose-jwt = "10.10"
yasson = "3.0.5"
redisson = "4.8.0"
netty = "4.2.18.Final"

lombok = "1.18.48"

guava-beta-checker = "1.0"

junit = "6.1.3"
mockito = "5.24.0"
assertj = "3.27.7"
rest-assured = "6.0.1"

eclipse-jdt = "4.40"
jspecify = "1.0.1"
errorprone = "2.50.0"
nullaway = "0.14.2"

[libraries]
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs-annotations" }
findsecbugs = { module = "com.h3xstream.findsecbugs:findsecbugs-plugin", version.ref = "findsecbugs" }

openliberty-runtime = { module = "io.openliberty:openliberty-runtime", version.ref = "openliberty" }

jakartaee-web-api = { module = "jakarta.platform:jakarta.jakartaee-web-api", version.ref = "jakartaee" }

slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

mongodb-driver-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb-driver" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus-jose-jwt" }
yasson = { module = "org.eclipse:yasson", version.ref = "yasson" }
redisson = { module = "org.redisson:redisson", version.ref = "redisson" }
netty-resolver-dns-native-macos = { module = "io.netty:netty-resolver-dns-native-macos", version.ref = "netty" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }

jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
guava-beta-checker = { module = "com.google.guava:guava-beta-checker", version.ref = "guava-beta-checker" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
nullaway = { id = "net.ltgt.nullaway", version.ref = "nullaway-plugin" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugs" }
liberty = { id = "io.openliberty.tools.gradle.Liberty", version.ref = "liberty-plugin" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[bundles]
testing = [
    "junit-api",
    "junit-params",
    "mockito-core",
    "mockito-junit",
    "assertj-core",
    "rest-assured"
]
